version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - STRIPE_PUBLIC_KEY=pk_test_51OouD1SEeO14Os1OKexmKjXIYj3ob0R2ptxEXsVq82RNd8uDAPNCkcHM1gAlaVq3gpYTpF91bBqbk4UTNZVX58Sw00Y1In5WpF
      - STRIPE_SECRET_KEY=sk_test_51OouD1SEeO14Os1OKexmKjXIYj3ob0R2ptxEXsVq82RNd8uDAPNCkcHM1gAlaVq3gpYTpF91bBqbk4UTNZVX58Sw00Y1In5WpF
    volumes:
      - .:/app
