version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - STRIPE_PUBLIC_KEY=YOUR_PUBLIC_STRIPE_KEY
      - STRIPE_SECRET_KEY=YOUR_SECRET_STRIPE_KEY
    volumes:
      - .:/app
